#!/usr/bin/env python3

import argparse
import subprocess
import sys
import os

parser = argparse.ArgumentParser(description="WACC Compiler.")
parser.add_argument('filename',
                    help="The file you wish to compile")
parser.add_argument('-d',
                    '--debug',
                    action='store_const',
                    const='True',
                    help="Gives further information useful for debugging")
parser.add_argument('-e',
                    '--exit_code',
                    action='store_const',
                    const='True',
                    help="Only prints exit code of compilation")

args = parser.parse_args()
filename = args.filename if args.filename else ""
debug = '-d' if args.debug else ''
exit_code_only = args.exit_code

stdout = None
stderr = None
if exit_code_only:
    stdout = subprocess.DEVNULL
    stderr = subprocess.DEVNULL

base_path = os.path.dirname(os.path.abspath(__file__))
frontend_path = os.path.join(base_path, 'frontend')

command = "cat {} | {} {}".format(filename, frontend_path, debug)

process_exit_code = subprocess.call(command, shell=True, stdout=stdout, stderr=stderr)

if exit_code_only:
    print(process_exit_code)

sys.exit(process_exit_code)
