#!/usr/bin/env python3

import argparse
import subprocess
import sys

parser = argparse.ArgumentParser(description="WACC Compiler.")
parser.add_argument('filename',
                    help="The file you wish to compile")
parser.add_argument('-d',
                    '--debug',
                    action='store_const',
                    const='True',
                    help="Gives further information useful for debugging")
parser.add_argument('-x',
                    '--exit-code',
                    action='store_const',
                    const='True',
                    help="Only prints exit code of compilation")


args = parser.parse_args()
filename = args.filename if args.filename else ""
debug = '-d' if args.debug else ''

if args.exit_code:
    command = "cat {} | ./frontend".format(filename)
    print(subprocess.call(command, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL))
else:
    command = "cat {} | ./frontend {}".format(filename, debug)
    print(filename, debug)
    sys.exit(subprocess.call(command, shell=True))
